apiVersion: v1
kind: Service
metadata:
  name: mc2
  namespace: minecraft
  annotations:
    "mc-router.itzg.me/externalServerName": "mc2.loibis.com"
spec:
  ports:
  - port: 25565
  selector:
    run: mc2