apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock
  namespace: minecraft
spec:
  type: ClusterIP
  ports:
  - port: 19132
    protocol: UDP
    targetPort: 19132
  selector:
    app: minecraft-bedrock