apiVersion: v1
kind: Service
metadata:
  name: minecraft-java
  namespace: minecraft
spec:
  type: ClusterIP
  selector:
    app: minecraft-java
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
