apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mc1
  name: mc1
  namespace: minecraft
spec:
  selector:
    matchLabels:
      run: mc1
  template:
    metadata:
      labels:
        run: mc1
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - image: itzg/minecraft-server
        name: mc1
        env:
        - name: TYPE
          value: FORGE
        - name: VERSION
          value: "1.12.1"
        - name: FORGE_VERSION
          value: "52.1.0"
        - name: FORGE_FORCE_REINSTALL
          value: "TRUE"
        - name: EULA
          value: "TRUE"
        - name: ONLINE_MODE
          value: "FALSE"
        ports:
        - containerPort: 25565
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mc1
